ai_enablement:
  - title: AI Basics
    description: Understanding AI fundamentals and navigating available tools and platforms
  - title: AI Workflow Transformation
    description: Integrate AI solutions into your existing workflows for maximum efficiency
  - title: AI Workspace Mindsets
    description: Develop the right approach and culture for AI adoption in your organization

data_solutions:
  - title: ETL Solutions
    description: Specialized in dbt implementations for modern data stack transformation
  - title: Looker Solutions
    description: Expert implementation and optimization of Looker for business intelligence 