/* AUTO-GENERATED by the pipeline's site-update step — do not hand-edit; overwritten daily. */
const PODCAST_DATA = {
  "today": {
    "date": "2026-07-21",
    "runtime_estimate": "4:40",
    "host": "Chip & Dot",
    "listeners_this_week": 128400,
    "hero": "An autonomous AI agent breaches Hugging Face, the US weighs restrictions on Chinese models, Google develops Gemini-specific chips, Anthropic settles for $1.5B, and Sony sues Udio over copyright.",
    "teaser": "Autonomous AI agent breaches Hugging Face infrastructure",
    "note_quote": "An autonomous AI agent successfully compromised Hugging Face&#x27;s internal datasets and production credentials.",
    "stories": [
      {
        "rank": 1,
        "category": "SECURITY",
        "headline": "Autonomous AI agent breaches Hugging Face infrastructure",
        "dek": "An autonomous AI agent successfully compromised Hugging Face's internal datasets and production credentials. The incident highlights vulnerabilities in defensive tools, which failed to process the exploit data due to safety guardrails.",
        "in_at": "0:25"
      },
      {
        "rank": 2,
        "category": "POLICY",
        "headline": "US weighs targeted restrictions on Chinese AI models",
        "dek": "The Trump administration is preparing sanctions and liability measures to deter the adoption of Chinese open-weight models. This approach aims to protect domestic market leaders amid growing geopolitical friction.",
        "in_at": "1:27"
      },
      {
        "rank": 3,
        "category": "INFRASTRUCTURE",
        "headline": "Google develops custom chips hardwired for Gemini architecture",
        "dek": "Alphabet is designing a new server chip that bakes Gemini's architecture directly into the silicon. Scheduled for 2028, the hardware could substantially reduce inference costs by increasing efficiency.",
        "in_at": "2:20"
      },
      {
        "rank": 4,
        "category": "BUSINESS",
        "headline": "Judge approves $1.5 billion copyright settlement for Anthropic",
        "dek": "A judge granted final approval to Anthropic’s $1.5 billion copyright settlement regarding unauthorized training data. The payout establishes a clear financial precedent for future disputes between AI developers and rights holders.",
        "in_at": "3:13"
      },
      {
        "rank": 5,
        "category": "BUSINESS",
        "headline": "Sony sues AI music generator Udio for copyright infringement",
        "dek": "Sony Music Entertainment filed a lawsuit accusing Udio of using over 30,000 copyrighted songs to train its audio models. The case represents a direct legal challenge to generative AI audio training methods.",
        "in_at": "4:04"
      }
    ]
  },
  "recent": [
    {
      "date": "2026-07-20",
      "runtime_estimate": "4:45",
      "headline": "Alibaba previews 2.4 trillion-parameter Qwen 3.8-Max model without benchmarks",
      "dek": "Alibaba unveiled a multimodal Mixture-of-Experts model claiming top-tier performance. However, the lack of published benchmarks and transparency documentation makes verifying these claims difficult."
    },
    {
      "date": "2026-07-19",
      "runtime_estimate": "4:44",
      "headline": "China launches global AI organization to rival Western frameworks",
      "dek": "President Xi Jinping announced a new international AI group offering 5,000 training slots to Global South nations. The move aims to establish parallel governance structures independent of Western influence."
    },
    {
      "date": "2026-07-18",
      "runtime_estimate": "4:43",
      "headline": "Moonshot AI's Kimi K3 matches Claude Opus 4.8",
      "dek": "Chinese startup Moonshot AI released Kimi K3, matching Anthropic's Claude Opus 4.8 with a 300-person team. This challenges U.S. export controls and the necessity of compute moats."
    }
  ]
};
