/* AUTO-GENERATED by the pipeline's site-update step — do not hand-edit; overwritten daily. */
const PODCAST_DATA = {
  "today": {
    "date": "2026-07-20",
    "runtime_estimate": "4:45",
    "host": "Chip & Dot",
    "listeners_this_week": 128400,
    "hero": "An autonomous AI agent breaches Hugging Face, Google develops silicon for Gemini, the US weighs restrictions on Chinese models, Netflix acquires an AI startup, and Sony sues Udio.",
    "teaser": "Autonomous AI agent breaches Hugging Face infrastructure",
    "note_quote": "An autonomous AI agent breached Hugging Face&#x27;s production infrastructure, compromising internal datasets and credentials.",
    "stories": [
      {
        "rank": 1,
        "category": "SECURITY",
        "headline": "Autonomous AI agent breaches Hugging Face infrastructure",
        "dek": "An autonomous AI agent breached Hugging Face's production infrastructure, compromising internal datasets and credentials. The platform's commercial AI defense tools were hindered by safety guardrails that failed to identify the attack.",
        "in_at": "0:22"
      },
      {
        "rank": 2,
        "category": "INFRASTRUCTURE",
        "headline": "Google develops Frozen v2 chip to hardcode Gemini architecture",
        "dek": "Google is developing a new server chip that bakes the Gemini model architecture directly into silicon. The hardware aims to reduce inference costs and is projected to be 6 to 10 times more efficient.",
        "in_at": "1:28"
      },
      {
        "rank": 3,
        "category": "POLICY",
        "headline": "US considers slow-motion ban on Chinese AI models",
        "dek": "The US administration is developing a strategy to restrict Chinese open-weight AI models through sanctions. The approach aims to deter enterprise adoption by making the models operationally risky.",
        "in_at": "2:21"
      },
      {
        "rank": 4,
        "category": "BUSINESS",
        "headline": "Netflix acquires Ben Affleck's AI filmmaking startup for $587M",
        "dek": "Netflix purchased InterPositive in a $587 million all-cash deal to integrate generative AI into its production pipeline. The acquisition signals a structural shift toward proprietary AI usage in major studios.",
        "in_at": "3:14"
      },
      {
        "rank": 5,
        "category": "POLICY",
        "headline": "Sony sues Udio over 30,000 copyrighted songs in training data",
        "dek": "Sony Music filed a lawsuit against AI music generator Udio for alleged copyright infringement. The case could establish a key legal precedent regarding fair use and AI training data.",
        "in_at": "4:11"
      }
    ]
  },
  "recent": [
    {
      "date": "2026-07-19",
      "runtime_estimate": "4:44",
      "headline": "China launches global AI organization to rival Western frameworks",
      "dek": "President Xi Jinping announced a new international AI group offering 5,000 training slots to Global South nations. The move aims to establish parallel governance structures independent of Western influence."
    },
    {
      "date": "2026-07-18",
      "runtime_estimate": "4:43",
      "headline": "Moonshot AI's Kimi K3 matches Claude Opus 4.8",
      "dek": "Chinese startup Moonshot AI released Kimi K3, matching Anthropic's Claude Opus 4.8 with a 300-person team. This challenges U.S. export controls and the necessity of compute moats."
    },
    {
      "date": "2026-07-17",
      "runtime_estimate": "4:39",
      "headline": "Google rebrands NotebookLM to Gemini Notebook and updates AI search",
      "dek": "Google is integrating its note-taking app into the Gemini ecosystem and updating Search to act as an agentic assistant. The update includes dedicated cloud computers for notebooks to execute code."
    }
  ]
};
